name: 🚀 Kono-Ha Custom Build
on:
  workflow_dispatch:
    inputs:
      hz:
        description: 'Pilih HZ (Responsivitas)'
        required: true
        type: choice
        options: ['100', '250', '500', '1000']
        default: '500'
      ksu_flavor:
        description: 'Pilih Rasa Root'
        required: true
        type: choice
        options:
          - official
          - ksu-next
          - sukisu
          - resukisu
          - mambosu
          - wild-ksu
          - none
        default: 'ksu-next'
      include_susfs:
        description: 'Suntik SusFS (Hide Root)?'
        required: true
        type: boolean
        default: false
      use_kpm:
        description: 'Aktifkan KPM?'
        required: true
        type: boolean
        default: false
      use_hardened:
        description: 'Mode Hardened?'
        required: true
        type: boolean
        default: false

jobs:
  launch:
    # Memanggil file logika konoha-logic.yml
    uses: ./.github/workflows/konoha-logic.yml
    with:
      hz: ${{ github.event.inputs.hz }}
      ksu_flavor: ${{ github.event.inputs.ksu_flavor }}
      # Konversi eksplisit ke boolean agar tidak error parser
      susfs: ${{ github.event.inputs.include_susfs == 'true' }}
      kpm: ${{ github.event.inputs.use_kpm == 'true' }}
      hardened: ${{ github.event.inputs.use_hardened == 'true' }}
    secrets: inherit
