name: Konoha Build Engine
on:
  workflow_call:
    inputs:
      hz:
        type: string
        required: true
      variant:
        type: string
        required: true
      ksu_flavor:
        type: string
        required: true
      kpm:
        type: boolean
        required: true
      hardened:
        type: boolean
        required: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Env
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential flex bison lld llvm-dev libssl-dev ccache libelf-dev rsync python3 git-lfs

      - name: Patch Root
        run: |
          # Mekanik pencarian root kernel kamu
          KROOT=$(find . -name "drivers" -type d | grep -E "common|msm-kernel" | head -n 1 | xargs dirname)
          cd $KROOT
          
          case "${{ inputs.ksu_flavor }}" in
            "ksu-next") curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/main/kernel/setup.sh" | bash -s main ;;
            "wild-ksu") curl -LSs "https://raw.githubusercontent.com/Wild-KSU/WildKSU/main/kernel/setup.sh" | bash -s main ;;
            "official") curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main ;;
          esac

          # Fix Kconfig
          sed -i '/kernelsu/d' drivers/Kconfig
          echo 'source "drivers/kernelsu/Kconfig"' >> drivers/Kconfig

      - name: Build Bazel
        run: |
          cd kernel_platform
          chmod +x build/android/prepare_vendor.sh
          chmod +x build/build_sun.sh
          ./build/android/prepare_vendor.sh sun
          
          # Gunakan ternary logic yang lebih aman
          LTO_VAL=$([[ "${{ inputs.kpm }}" == "true" ]] && echo "thin" || echo "full")
          
          LTO=$LTO_VAL HZ=${{ inputs.hz }} ./build/build_sun.sh

      - name: Upload
        run: |
          git clone --depth=1 https://github.com/osm0sis/AnyKernel3
          IMAGE=$(find out -name "Image" | head -n 1)
          cp "$IMAGE" AnyKernel3/
          cd AnyKernel3
          zip -r9 "../Kono-Ha-${{ inputs.ksu_flavor }}-${{ inputs.hz }}hz.zip" .
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kono-Ha-${{ inputs.ksu_flavor }}-${{ inputs.hz }}hz
          path: "*.zip"
