name: Kono-Ha Manual Build UI
on:
  workflow_dispatch:
    inputs:
      hz:
        description: 'Pilih HZ'
        required: true
        type: choice
        options: ['100', '250', '500', '1000']
        default: '500'
      variant:
        description: 'Varian Dasar'
        required: true
        type: choice
        options: ['stock', 'root', 'susfs']
        default: 'root'
      ksu_flavor:
        description: 'Pilih Root Flavor'
        required: true
        type: choice
        options: ['ksu-next', 'sukisu', 'resukisu', 'mambosu', 'wild-ksu', 'official', 'none']
        default: 'ksu-next'
      kpm:
        description: 'Aktifkan KPM?'
        required: true
        type: boolean
        default: false
      hardened:
        description: 'Mode Hardened?'
        required: true
        type: boolean
        default: false

jobs:
  call-engine:
    uses: ./.github/workflows/konoha-engine.yml
    with:
      hz: ${{ github.event.inputs.hz }}
      variant: ${{ github.event.inputs.variant }}
      ksu_flavor: ${{ github.event.inputs.ksu_flavor }}
      kpm: ${{ github.event.inputs.kpm == 'true' }}
      hardened: ${{ github.event.inputs.hardened == 'true' }}
    secrets: inherit
